dist: trusty
language: java
jdk:
  - oraclejdk8
notifications:
  email:
    recipients:
      - cibuilds@duracloud.org
    on_success: change
    on_failure: always
  slack: duraspace:vOBySuKUwM95j2kfbwh0SNxq
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libaio1
install:
  - mvn install -DskipTests --batch-mode
script:
  - mvn test -DskipIntTests
sudo: true
env:
  global:
    - secure: "WYJqVIM38eyZ/mkvWv8DIaywLCYFqfvLLS8RKpZBNjMJT2/SssKiBAeXeruJt4XP/RWiCKTVLHQvDGgBSG36wl9tY8wnmsQ89zo5kbYSork4dnOFgoCZ6XkGChy5Vcy1ieY/qnpd3wVGrnDkicPQnGBzpU+J9Q+u9upkCOChzDjrJnI9h6ObJ80BdxlnKC80O/jhwPbg7X9lODVuzZStyVPoa1mZzJrtvtFWSEJ9DUdFdQCnnkArlItoETGJtPNyfeRLNIzU7yRDBbojUwjamWuKYt5NS24ZVKtRyQVQwmq3BOZhLLSapVwDjqYW9r0ju2cGB4Fg3ZMVS7UHHKMBGLwktYamkYLgb2foOnG60RcjMLDFYEYxROfZXmvNodNqqwnJtXbXBTN1Jc5zHSQ5AL2IWPPIqFZSDdN64Em/FMcFpIb1CzNnypvu2Zs/+4WHFoc+cEgQ2EgH+GZJcGg5SDjoq/wUz1WXIO4123BtOnJbMoO1fhWaMeF2sMML9FHB0PCtnOmSxophg7qr9B6I4kJxhphOa5lVqRh7j63AqcthcV1TH3EMF3XAyDRWQ0IHiPsXfda9SxDULZjwQT+kzpt/oFzPa1xeK/yb0inX0UcBOKmiL7UpowdPSMFYEdXM+uEmnam2C266RhRuiEh+4Ql8NRA8NahQ5rTc7MEc9S8="
    - # ^^ SONATYPE_USERNAME
    - secure: "iH9w49tzAFRkl/i4CZKFJzv4ouzoXyknGrVwbcV+yk5YQpz/SE3uPmNwlMEqrWl0LEU/FMPP809NR8+Upt5ctsYbtMdRH3PpH04b7M1X+5YYBtrYOZQG5b7oQCzUP7e3AIup4iL+uqzgMtnW/5I6G87jzGyz6AYRvZiZRVTgs+NYyCx/vB3CL6V7WfW7gMmni9LPGUEllxMtQrNiRc562JPLr6JopsCGCF+cdy6YPSNh8NsSTrFTcmlcJ1e97bh4bohOx1+4ume6eVfVPc9lQl/7tas5+jFKZxi69kpK0mNTWSnks6tmm3J98x0vxhxWvPTRZNh/HCooErx5ssHCN0Cr3UoXvFPyfOTd2BQMkX8ONX+DFnHDPeGt2y07fNZgNqfnyUmaB6kxsvq6De6SYOEu9NuEzNLNLLE4t5eg5ORltsqgseGDtNRfBaPzpuIneOYrVsOo2NenpVQ2KRc1+xVH2r7zjrX74P4FBljv3FZhxw2Ur1q/KCBBGIXtUeS8qbvH8zl8e92Ubo7xgQQU87M8jr8gSpWrnSpEGRDdKooGxjTUS4FmtBXcZfhWlSctbbZHHTQ8gL/P2KB4ymHvozXTxUjsgBDO35nSVvRb9FRSbE0K0bVheebJjMXs3BCb6o/LAtmWyZ/k3kfPoCHE4Qt7oTGsM6f6LyPHx4CVuYg="
    - # ^^ SONATYPE_PASSWORD
    - secure: "dOAYI/K3gBciHLkYNgfFrChJGda46CndmpdcWiIYl+zKQ9A10FknC/7kstp3QDbvWGEoDEF5Ey3t8qbKYRIcbgg4tKIVv79I8uCQ5ZnldDu6ZsXW3AKc/FyXnvqs2tEiJXDVXRGTY3CqpA4nrFqjHyHBNj4PQgz1SOlP1b+355F+XPmfG33HcUWPG+nMGr/+jBuMOVBqccrsmYOu7b2GPbzQQPDklReg42R/4cMh6okHRUb7reZYXEU5GVQz1oUGjPMGw6bp9IOHWvDbfHC9L9eGkua9ypFHuvXpdD5xPBec2njUFK7ZC3JagEbYQrwz7u3WzBg8YzU9IB06E0kFxkojmLz046nsELq+0tCiBM9IbB3o3fj7R8bxgKf1stTWzwut8EbqsUrVtbzwIzkPoaPnXUrKd/gX8khe9yTDDbnYXqYNwuiXr7Ld7Kwf0YuSpnSQm/o00/hPOjylTQpChJ5DvSLJyJ/775eyos/Xj6ZWK8TQHF9+NCA4TA5LBu7JTfsDoEpNy211hQGbUpYAn2j807jH7A26FQ8fb5OJGDpkA6t/8yoi3deA5iJRb/40Tmz9HKo59ZIJxVPmNScQlcRLPhqkkATQR17TqhvuZbwu1Xtfw9obMJWejt6CL6Z5iH1BqG5GiTjRB/waQRYiQ1bmHj6OJMwuyURcS7j370g="
    - # ^^ GPG_KEY_NAME
    - secure: "fI+v//GXPAdqtPBoanDlay+KAGS7uFCkvaKssQC7kwE8z964rBsH1zKQMWI5nR2HaUw4RP8LknhAL1EgKZZRuitaNcZI7obug2Xr0fYofXPtQjwwx/kIubi5dvcGWYDX1eTPH5mi5gFA/7M7WQbsV4IuHo524jxS33/BspVRQFTQjaX4wpfxuqUEkB6hwuRIyeHryT5309q1RhOqC7W1D94jdzbr2ULmsJlvgfh31Afyjmupgf2VtDZbBZiZc28kVkEK8/ddEo8oSwFg2Ubn4wnj/81UnlFoNBPqpx70XuYNxJWV6sNRsZ1rWm29U1MhV1o5qJSdK1jiT3x6DK+vm+1WJkaCYWOcbEmJXEF1+m9Z5YIFxHo+CxMJ5pjXwNd+2VW2VMiVxWYS7RUkGuJZ+6dcDmXzowbb7NJuyG2bN0pvFnD12lgirfwfiPJt3XFLR3JSEr3NZWodAwmGSh8Zrfeo0EGa8Wdf+pkZdZgHYnFqkW9GJcpG5zlyiTQ8kaxd1+jofjnQQOsxykghXhwZehjsNBH6QB86blD11bAmbhpOSbgnfDg9w7EgtNufICB43RB99phXxTVFXdmH/9V7BckxWPlFz2bIp8+imJxC+UAa7ovW06E/+iHBHIuAA/KYvMDwTaAbddK4F99fwjfeqT5cUZngh8qbmvGMYoj6Y4Y="
    - # ^^ GPG_PASSPHRASE
after_success:
  - chmod +x resources/travis/*.sh
  - ./resources/travis/before-deploy.sh
  - ./resources/travis/deploy.sh
